### ISSUE TITLE
"三个故事" 文章中有笔误 "前对不上了"

### ISSUE THREAD

**Issue by DevDengChao** [plantegg/programmer_case#3]
![image](https://user-images.githubusercontent.com/16363180/228849722-264912f0-e499-4e3f-b74b-72553bd5f591.png)

https://plantegg.github.io/2022/01/01/%E4%B8%89%E4%B8%AA%E6%95%85%E4%BA%8B/

**Comment by plantegg** [comment]
已改正，谢谢纠错
